// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-MueSjPzghxBVD1QxtYyFPAAJMOxcdU',
    appId: '1:691811953242:web:12bf8c00f0bdd2c8aa0663',
    messagingSenderId: '691811953242',
    projectId: 'mainproject-213b5',
    authDomain: 'mainproject-213b5.firebaseapp.com',
    storageBucket: 'mainproject-213b5.firebasestorage.app',
    measurementId: 'G-RKP3VNYHM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGCOdTnepi0PJtYbxOj_m8gAfbBinuC4',
    appId: '1:691811953242:android:bf98596b0e0e9c0aaa0663',
    messagingSenderId: '691811953242',
    projectId: 'mainproject-213b5',
    storageBucket: 'mainproject-213b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJJhTbgaCXxe6yRpdHgQIRam6wuGIrP8',
    appId: '1:691811953242:ios:27b8f1733d7ad843aa0663',
    messagingSenderId: '691811953242',
    projectId: 'mainproject-213b5',
    storageBucket: 'mainproject-213b5.firebasestorage.app',
    iosBundleId: 'com.example.bantayPamilya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnJJhTbgaCXxe6yRpdHgQIRam6wuGIrP8',
    appId: '1:691811953242:ios:27b8f1733d7ad843aa0663',
    messagingSenderId: '691811953242',
    projectId: 'mainproject-213b5',
    storageBucket: 'mainproject-213b5.firebasestorage.app',
    iosBundleId: 'com.example.bantayPamilya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkVEnqIj8ezUuHiwm0vLNFo9fviPWn0o',
    appId: '1:691811953242:web:3b5084aa6753d93faa0663',
    messagingSenderId: '691811953242',
    projectId: 'mainproject-213b5',
    authDomain: 'mainproject-213b5.firebaseapp.com',
    storageBucket: 'mainproject-213b5.firebasestorage.app',
    measurementId: 'G-GD4HBFYKLV',
  );
}
